export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const ADD_STORES = 'ADD_STORES';
export const ADD_CURRENT_CATEGORY = 'ADD_CURRENT_CATEGORY';
export const ADD_SELECTED_STORES = 'ADD_SELECTED_STORES';
export const ADD_PAGINATION = 'ADD_PAGINATION';
