export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const ADD_STORES = 'ADD_STORES';
export const ADD_CURRENT_CATEGORY = 'ADD_CURRENT_CATEGORY';
export const ADD_SELECTED_STORES = 'ADD_SELECTED_STORES';
export const ADD_PAGINATION = 'ADD_PAGINATION';
export const SET_CART = 'SET_CART';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const SET_TOAST_MESSAGE = 'SET_TOAST_MESSAGE';
export const GET_CART = 'GET_CART';

